version: "3.7"

services:
  demo:
    image: "${DOCKER_IMAGE_NAME}"
    ports:
    - "8080:8080"
    environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    links:
    - redis
  redis:
    image: redis
